name: web-CICD

on:
  schedule:
    - cron: "0 10 * * *"
  push:
    branches:
      - main
    paths:
      - src/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build Docker image
        run: |
          IMAGE_TAG=$(echo "${{ github.sha }}" | cut -c1-8)
          echo "Building zarrcloud/portfolio:${IMAGE_TAG}"
          docker build \
            -t zarrcloud/portfolio:${IMAGE_TAG} \
            -t zarrcloud/portfolio:latest \
            .

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          kubectl get nodes


      - name: Push & Deploy via Helm
        run: |
          IMAGE_TAG=$(echo "${{ github.sha }}" | cut -c1-8)

          # Push the newly built image
          docker push zarrcloud/portfolio:${IMAGE_TAG}
          docker push zarrcloud/portfolio:latest

          # Deploy using the chart at helm/webapp (relative to repo root)
          helm upgrade webapp webapp_pipeline/app \
            --set image.tag=${IMAGE_TAG} \
            --reuse-values

      - name: Wait for rollout to finish
        run: |
          kubectl rollout status deployment/portfolio-deployment \
            --namespace default --timeout=120s

